apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-web
    spec:
      containers:
        - name: eks-ecr-argocd
          image: 061039771693.dkr.ecr.ap-northeast-2.amazonaws.com/eks-ecr-argocd:latest
