apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-web
    spec:
      containers:
        - name: eks-app
          image: 061039771693.dkr.ecr.ap-northeast-2.amazonaws.com/eks-ecr-argocd:8d0d9b8a88a7f5e98ac705f08e0365a5cad31c8f
