apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-web
    spec:
      containers:
        - name: eks-app
          image: 061039771693.dkr.ecr.ap-northeast-2.amazonaws.com/eks-app:70cb3707466cacb04cbfdd8d061d2a1094184196
          ports:
          - protocol: TCP
            containerPort: 8080
