apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    type: local
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500Mi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3
  hostPath:
    path: /home/ubuntu/app-with-argocd-project/mysql/data
